services:
  - type: web
    name: smart-traffic-raipur
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python backend/app.py
    envVars:
      - key: ORS_API_KEY
        sync: false